djangoSite/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView

urlpatterns = [
    url(r"^$", TemplateView.as_view(template_name="index.html")),
    url(r"^phoenix/", TemplateView.as_view(template_name="phoenix.html")),
    url(r"^george/.*", TemplateView.as_view(template_name="badLink.html")),
    url(r'^polls/', include('polls.urls', namespace="polls")),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^icarus/', include('icarus.urls', namespace="icarus")),
    url(r'^is/', include('intellectualSharing.urls', namespace="is")),
    url(r'^regex/', include('regex.urls', namespace="regex"))
]

icarus/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
	url(r'^$', views.index, name = 'index'),
	url(r'^recordHighScore$', views.recordHighScore, name = 'recordHighScore'),
	url(r'^getLeaderboard$', views.getLeaderboard, name='getLeaderboard')
]

polls/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
	url(r'^$', views.index, name = 'index'),
	url(r'^(?P<question_id>[0-9]+)/$', views.detail, name='detail'),
	url(r'(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
	url(r'(?P<question_id>[0-9]+)/addChoice/$', views.addChoice, name='addChoice'),
	url(r'^addQuestion/$', views.addQuestion, name='addQuestion')
]

regex/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
	url(r'^$', views.index, name = 'index'),
	url(r'^search$', views.search, name='search'),
]

icarus/models.py
from django.db import models
from datetime import datetime;

class highScore(models.Model):
	score = models.IntegerField(default=0)
	user = models.CharField(max_length=50)
	creationDate = models.DateTimeField(default=datetime.now, blank=True)

	def __str__(self):
		return "score: " + str(self.score) + "  user: " + str(self.user)

polls/models.py
from django.db import models
from django.utils import timezone
import datetime

class Question(models.Model):
	question_text = models.CharField(max_length=200)
	pub_date = models.DateTimeField('date published')
	
	def __str__(self):
		return self.question_text
	
	def was_published_recently(self):
		now = timezone.now()
		return now - datetime.timedelta(days=1) <= self.pub_date <= now

class Choice (models.Model):
	question = models.ForeignKey(Question)
	choice_text = models.CharField(max_length=200)
	votes = models.IntegerField(default=0)
	
	def __str__(self):
		return self.choice_text

class ipAlreadyVoted(models.Model):
	question = models.ForeignKey(Question)
	ip = models.CharField(max_length=60)
	
	def __str__(self):
		return self.ip

djangoSite/views.py
from django.shortcuts import render, get_object_or_404, render_to_response

def home(request):
	return render(request, 'index.html')

icarus/views.py
from django.shortcuts import render
from django.shortcuts import render, get_object_or_404, render_to_response
from django.http import HttpResponse, Http404, HttpResponseRedirect
from .models import highScore
import logging

logger = logging.getLogger(__name__)

def index(request):
	return render(request, "icarus.html");

def recordHighScore(request):
	
	if request.GET.get('identity') == 'millercodesIcarus':
		if not(request.GET.get('score').isdecimal()) or not(isinstance(request.GET.get('user'), basestring)):
			return HttpResponse('Invalid Arguments')
		
		sameUserObjects = highScore.objects.filter(user=request.GET.get('user'))
		logger.error("Found entires with same user " + str(sameUserObjects))
		if sameUserObjects != []:
			for sameUser in sameUserObjects:
				if sameUser.score > request.GET.get('score'):
					return HttpResponse('This user has a high score saved')
			# If we didn't return, then this score is the
			# current highest for this user, so we must delete the redundant entries
			sameUserObjects.delete()

		hs = highScore()
		hs.score = request.GET.get('score')
		hs.user = request.GET.get('user')
		hs.save()
		return HttpResponse('Successfly saved high score')
	
	return HttpResponse('you are not a valid user')

def getLeaderboard(request):
	scores = [];
	scoreObjects = highScore.objects.all().order_by('-score')
	for scoreObj in scoreObjects:
		scores.append("score: " + str(scoreObj.score) +
			"  user: " + scoreObj.user + " <br/> ") 
	return HttpResponse(scores)

polls/views.py
from django.shortcuts import render, get_object_or_404, render_to_response
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.template import RequestContext, loader
import logging
from .models import Question, Choice, ipAlreadyVoted
from django.views import generic
from django.core.urlresolvers import reverse
from django.utils import timezone
from django.views.decorators.csrf import csrf_exempt

logger = logging.getLogger(__name__)
def get_client_ip(request):
	x_forwarded_for = request.META.get('HTTP_X_FORWARDED_FOR')
	if x_forwarded_for:
		ip = x_forwarded_for.split(',')[0]
	else:
		ip = request.META.get('REMOTE_ADDR')
	return ip

def index(request):
	return render(request, 'polls/index.html', {'latest_question_list': Question.objects.all()})

def detail(request, question_id):
	return render(request, 'polls/detail.html', {'question': Question.objects.get(pk=question_id)})


def vote(request, question_id):
	p = get_object_or_404(Question, pk=question_id)
	logger.error(p);
	try:
		selected_choice = p.choice_set.get(pk=request.POST['choice'])
	except (KeyError, Choice.DoesNotExist):
		# Redisplay the question voting form.
		return HttpResponse("You didn't select a choice.")
	else:
		logger.error(selected_choice);
	if p.ipalreadyvoted_set.filter(ip=get_client_ip(request)).count() == 0:
		selected_choice.votes += 1
		ip = ipAlreadyVoted(ip=get_client_ip(request), question_id=p.id)
		ip.save()
		p.ipalreadyvoted_set.add(ip)
		selected_choice.save()
		p.save()
		return HttpResponseRedirect(reverse('polls:detail', args=(p.id,)))
	else:
		return HttpResponse("You already voted")

def addChoice(request, question_id):
	question = get_object_or_404(Question, pk=question_id)
	for choice in question.choice_set.all():
		if choice.choice_text == request.POST['newChoice']:
			return HttpResponse("Choice already exists")
			
	newChoice = Choice(question_id=question.id)
	newChoice.choice_text = request.POST['newChoice']
	newChoice.save()
	question.choice_set.add(newChoice)
	question.save()
	return HttpResponseRedirect(reverse('polls:detail', args=(question.id,)))


def addQuestion(request):
	for question in Question.objects.all():
		if question.question_text == request.POST.get('newQuestion', False):
			return HttpResponse("Question already exists");
	
	newQuestion = Question(question_text=request.POST.get('newQuestion', False), pub_date=timezone.now())
	newQuestion.save()
	return HttpResponseRedirect(reverse('polls:index'))

regex/views.py
from django.shortcuts import render
from django.shortcuts import render, get_object_or_404, render_to_response
from django.http import HttpResponse, Http404, HttpResponseRedirect
from lib.python.regex import findall, compile

def index(request):
    return render(request, 'regex.html')

def search(request):
    graph = compile(request.POST['regex'])
    found = findall(request.POST['collection'], graph)
    return render(request, 'regex.html', {
        'results': found
    })

polls/templates/polls/detail.html
{% load staticfiles %}
{% load get_range %}
<head>
<link rel='shortuct icon' href='/george/static/favicon.ico'>
<link rel='stylesheet' type='text/css' href='{% static "bootstrap/normalize.css" %}'/>
<link rel='stylesheet' type='text/css' href='{% static "bootstrap/bootstrap.css" %}'/>
<link rel='stylesheet' type='text/css' href='{% static "polls/style.css" %}'/>

</head>
<body>

<h1 id="question" name="{{ question.id }}">{{ question.question_text }}</h1>

<p><strong id="errorMessage"></strong></p>

{% for choice in question.choice_set.all %}
<div class='row'>
<div class='inputContainer'>
	<div class='radioButton' name='unselected' id="{{ choice.id }}"><span>{{ choice.choice_text }}</span></div>
</div>
<div class="voteMeterParent">
	{% for i in choice.votes|get_range %}
	<div class="voteMeter"></div>
	{% endfor %}	
</div>
<div class='numOfVotes'>
	<span> {{ choice.votes }} votes</span>
</div>
</div>
{% endfor %}
<br/>
<div class="voteButton">Vote</div>
<br/>
<h4>Add another choice:</h4>
<form>
<input id="newChoice" type='text' name="newChoice" placeholder=" New Choice">
<input id="newChoiceSubmit" type="button" value="Submit"/>
</form>
<br/>
<hr/>
<a href='{% url 'polls:index' %}'>Back to Question Select</a>

<script src='{% static "jquery.js" %}'></script>
<script src='{% static "polls/detail.js" %}'></script>
<script>
$.ajaxSetup({
	data: {csrfmiddlewaretoken: '{{ csrf_token }}'},
});
</script>
</body>

polls/templates/polls/detailWithHTMLForms.html
{% load staticfiles %}
{% load get_range %}
<head>
<link rel='stylesheet' type='text/css' href='{% static "bootstrap/normalize.css" %}'/>
<link rel='stylesheet' type='text/css' href='{% static "bootstrap/bootstrap.css" %}'/>
<link rel='stylesheet' type='text/css' href='{% static "polls/style.css" %}'/>

</head>
<body>

<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
<div class='row'>
<div class='inputContainer'>
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label>
</div>
<div class="voteMeterParent">
	{% for i in choice.votes|get_range %}
	<div class="voteMeter"></div>
	{% endfor %}	
</div>
<div class='numOfVotes'>
	<span> {{ choice.votes }} votes</span>
</div>
</div>
{% endfor %}
<br/>

<input type="submit" value="Vote" />
</form>
<br/>
<h4>Add another choice:</h4>
<form action="{% url 'polls:addChoice' question.id %}" method="post">
{% csrf_token %}
<input type='text' name="newChoice" placeholder=" New Choice">
<input type='submit' value="Submit" />
</form>
<br/>
<hr/>
<a href='{% url 'polls:index' %}'>Back to Question Select</a>

<script src='{% static "jquery.js" %}'></script>
<script src='{% static "polls/detail.js" %}'></script>
</body>

polls/templates/polls/index.html
{% load staticfiles %}
<head>
<link rel='shortuct icon' href='/george/static/favicon.ico'>
<link rel='stylesheet' type='text/css' href='{% static "bootstrap/normalize.css" %}'/>
<link rel='stylesheet' type='text/css' href='{% static "bootstrap/bootstrap.css" %}'/>
<link rel='stylesheet' type='text/css' href='{% static "polls/style.css" %}'/>
</head>

<body>

<h1>Millercodes Polls</h1>
<h6>Pick a question to see votes, and vote yourself</h6>
{% if latest_question_list %}
	<ul>
	{% for question in latest_question_list %}
		<li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
	{% endfor %}
	</ul>

{% else %}
	<p>No polls are available.</p>
{% endif %}
<h6>Or start a new question!</h6>

<p><strong id="questionError"></strong></p>
<form>
<input type='text' id='newQuestion' placeholder=' New Question' />
<input id="newQuestionSubmit" type='button' value='Submit' />
</form>
<br/>
<hr/>
<a href="..">Go back to the homepage</a>

<script src='{% static "jquery.js" %}'></script>
<script src='{% static "polls/index.js" %}'></script>
<script>
$.ajaxSetup({
	data: {csrfmiddlewaretoken: '{{ csrf_token }}'},
});
</script>
</body>

templates/badLink.html
<!DOCTYPE html>

<head></head>

<body>
    This page has been moved to <a href='/'>here</a>
</body>

templates/icarus.html
<!DOCTYPE html>
<head>
</head>
<body>
	<h1>Icarus API</h1>
	<p>This page documents an API that I created using django.  My <a target="blank" href="https://play.google.com/store/apps/details?id=com.millercodes.icarus">app on the play store</a> uses this API to record scores and to view other people's scores.</p>
	<a href="getLeaderboard">View the LeaderBoard</a>
	<br/>
	<br/>
	A simple GET request is used to post scores to the leaderboard.  The GET request collects information like username and score and add it onto the database.  When the same user posts a new score, we delete their old score if it is lower than their new score.  If I gave you example links I would be risking my leaderboard's accuracy. 
</body>

templates/index.html
<!DOCTYPE html>
<head>
	<title>George's Server</title>
</head>

<body>
	<img src="/node/img/humanComputer.png" style="float:left;margin-right:20px;width:10%;min-width:200px;" />
	<h1>George Miller's Server</h1>
	<p>A place where I expermient, and have fun learning about the web.</p>
	<h2><a href="http://georgemyersmiller.com/portfolioSite/">Portfolio Site</a></h2>
	Current Projects: 
    <a href="/guitarKeyViewer/">Guitar Key Viewer</a>
	&nbsp;&nbsp;
    <a href="/regex/">Regular Expression Parser</a>
	&nbsp;&nbsp;
    <!--
    <a href="/is/">Django: Intellectual Sharing</a>
	&nbsp;&nbsp;
    --!>
    <a href="/phoenix">Phoenix Thought Process</a>
	<br/><br/>
	Previous Projects:
    <a href="/db/">Database Design Website</a>
	&nbsp;&nbsp;
    <a href="/node/">Node.js: ChatApp</a>
	&nbsp;&nbsp;
	<a href="/polls">Django: Polls</a>
	&nbsp;&nbsp;
	<a href="/icarus">Django API: Icarus</a>
    <p>All projects are free and open source! Check them out on my <a href="https://github.com/george-miller" target="blank">github</a> </p>
</body>

templates/phoenix.html
<!DOCTYPE html>
<head></head>
<body>
{% load staticfiles %}
<h1>Phoenix Thought Process</h1>
<a href='https://github.com/george-miller/phoenixThoughtProcess'>Code for this Java Applet on Github</a>
<br/>
<a href='{% static "PhoenixThoughtProcess.pdf" %}'>Document Entailing Thought Process</a>
<p>There is no game here yet because not enough code has been written! I am still analyzing and designing the game. Check out the document for more info!</p>
</body>

templates/regex.html
<!DOCTYPE html>
<html>
<head>
    </head>
<body>
	<h1>Regular Expression Parser</h1>
    <p>As a project for my Natural Language Processing class, I wrote a regular expression parser.  This program takes in a <a href="">regular expression</a> and uses it to search some collection of text for instances of that regular expression.</p>
    <form action='search' method='POST'>
        {% csrf_token %}
        <label>Input your collection of text to be searched <br/><textarea name='collection'></textarea></label>
        <br/>
        <label>Input your regular expression <br/><textarea name='regex' /></textarea></label>
        <br/>
        <input type='submit'>
    </form>
    {% if results != None %}
    <p>
    {% for result in results %}
    {{result}}
    <br/>
    {% endfor %}
    </p>
    {% endif %}
</body>
</html>